name: CI

on:
  pull_request:
    branches: ['main', 'dev']

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1

      - name: Create .env
        env:
          ENV_NAME: ${{ secrets.ENV_NAME }}
          ENV: ${{ secrets.ENV }}
        run: |
          touch ./$ENV_NAME
          echo "$ENV" > ./$ENV_NAME
      - name: Build
        run: |
          yarn add next
          npm install -save next --legacy-peer-deps
          CI=false npm run build
        shell: bash
